name: "JFrog Advanced Security for Juice Shop"

on:
  pull_request_target:
    types: [opened, synchronize]
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  pull-requests: write
  security-events: write

jobs:
  jfrog-advanced-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up JFrog CLI with OIDC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}/
        with:
          oidc-provider-name: frogbot

      - name: Ping JFrog Platform
        run: jf rt ping

      # Configure npm for Artifactory
      - name: Configure npm for Artifactory
        run: jf npmc --repo-resolve steffes-gh-npm

      # Patch postinstall script to use jf npm install
      - name: Patch postinstall script
        run: |
          sed -i 's/npm install/jf npm install/g' package.json

      # Install root npm dependencies
      - name: Install root npm dependencies
        run: jf npm install

      # Run Xray Advanced Security Scan
      - name: Xray Advanced Security Scan
        run: jf audit --watches="AnyBuildWatch"

      # Frogbot - SCA Fix PRs (Separate)
      - name: Frogbot - SCA Fix PRs (Separate)
        uses: jfrog/frogbot@v2
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ github.event.pull_request.base.ref || 'master' }}
          JF_INSTALL_DEPS_CMD: "jf npm install --legacy-peer-deps"
          JF_SCAN: "sca"
          JF_GIT_AGGREGATE_FIXES: "FALSE"
          JF_FIXABLE_ONLY: "TRUE"
        with:
          oidc-provider-name: frogbot

      # Frogbot - SCA Fix PR (Aggregated)
      - name: Frogbot - SCA Fix PR (Aggregated)
        uses: jfrog/frogbot@v2
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ github.event.pull_request.base.ref || 'master' }}
          JF_INSTALL_DEPS_CMD: "jf npm install --legacy-peer-deps"
          JF_SCAN: "sca"
          JF_GIT_AGGREGATE_FIXES: "TRUE"
          JF_FIXABLE_ONLY: "TRUE"
        with:
          oidc-provider-name: frogbot
