name: "JFrog SAST Scan"

on:
  workflow_dispatch: # Manual trigger

permissions:
  id-token: write            # Required for OIDC
  contents: read
  security-events: write     # Required to upload SARIF results

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'   # Juice Shop requires Node 22

    - name: Setup JFrog CLI with OIDC
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: https://${{ vars.JF_URL }}/
      with:
        oidc-provider-name: frogbot

    # Optional: configure npm for Artifactory (if needed for deps)
    - name: Configure npm for Artifactory
      run: jf npmc --repo-resolve steffes-gh-npm

    # Patch postinstall script to use jf npm install
    - name: Patch postinstall script
      run: |
        sed -i 's/npm install/jf npm install/g' package.json

    - name: Install project dependencies
      run: jf npm install

    - name: Run JFrog SAST scan
      run: jf audit --sast --format=sarif > jfrog_sast.sarif

    - name: Upload SAST scan results to GitHub Security Dashboard
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: jfrog_sast.sarif
